title: Vedran Živković # your name (or website title) here
logo: "/images/portret.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br> AR Developer and Game designer <br>
  <br><br>
  <a href="https://www.linkedin.com/in/vedran-%C5%BEivkovi%C4%87-75698532//">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://www.instagram.com/okvizv//">View My Instagram Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
